### ISSUE TITLE
patcher.exe isn't found

### ISSUE THREAD

**Issue by regularentropy** [Floorp-Projects/Floorp-AutoPatcher#2]
At the end of the execution the programme gives the following error 
![image](https://user-images.githubusercontent.com/89523758/209986859-4bf0e037-2588-4a07-92eb-5c607a1c9354.png)

**Comment by typeling1578** [comment]
This tool will be used in future tools to be released. Please wait.

**Comment by typeling1578** [comment]
published
https://github.com/Floorp-Projects/Floorp-Portable
